services:
  client:
    build: .
    command: ./.docker/start.sh
    volumes:
      - .:/home/node/client
    ports:
      - 3000:3000

# /etc/hosts

#IP do gateway host.docker.internal


#127.0.0.1 host.docker.internal