import { AppProvider } from './context/AppContext';
import './globals.css';

const metadata = {
  user: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
      <html lang='en'>
        <body className='bg-[#141414] text-white scrollbar-hide'>
        <AppProvider>
          {children}
        </AppProvider>
        </body>
      </html>
  );
}